### PR TITLE
Add intercities/cities filter

### LINKED ISSUE #829: Ajouter des filtres sur la liste de datasets
Filtres : 
- réseaux urbains
- réseaux interurbains
- tous les types de données qu'on a en tuiles sur la home

Use case pour interurbain/urbain : 
Tictactrip qui ne prend pas les réseaux urbains (Rome2Rio aussi il me semble), et qui doit parcourir, région par région, toute la liste pour trouver les jeux interurbains (régionaux). Situation inverse pour Mybus, transit...

Et peut-être aussi un moyen de filtrer là-dessus dans l'API ?

### PR DESCRIPTION
**Pull request by l-vincent-l**
Add this filter
image
fix #829

### CODE REVIEW

**Comment by antoine-de** [comment]
hum I'm not utterly convinced by the `interurbain` filter.
it does not seem to work well with the non pt datasets.
It selects :

image


don't you think it will be counter intuitive?
what do you think @sabinesafi?

**Comment by sabinesafi** [comment]
It should only show public transit data, published by regional agencies.

**Comment by Tristramg** [comment]
What is the status of this pull request? Should it be updated or closed?

**Comment by sabinesafi** [comment]
The filter is not in place so it's still pending.
To show public transit data at département or region level (but Nouvelle Aquitaine Mobilité has published both city data and regional data for instance, so we cannot apply a filter that's solely based on the publisher.

**Comment by Tristramg** [comment]
So, I suppose the solution would the filter to :

* Transport en commun régional
* Transport en commun urbain

To avoid abiguities (this would require an update in the code)

**Comment by antoine-de** [comment]
I updated the PR to also filter on the public-transport.

The labels are:
in french:
* Transport en commun urbain
* Transport en commun régional

in english:
* Urban public transport
* Intercities public transport

I'm not utterly convinced by them, feel free to suggest better ones :wink:

**Comment by Tristramg** [comment]
Good for me. Rebase and merge?

**Pull request merged**
