### PR TITLE
Remove Google's gtfs-validator integration

### PR DESCRIPTION
**Pull request by Tristramg**
partial_fix #185

### CODE REVIEW

**Comment by maukoquiroga** [comment]
It is OK 😃 . I'd wait though for the replacement of the _validate_data_ task to be replaced with ```datatools``` before merging, as otherwise it'd be IMHO a regression.

**Comment by Tristramg** [comment]
:+1: and done

Concerning Docker, maybe we could build it on dockerhub directly from the github instead of pushing by hand? What do you think?

**Comment by maukoquiroga** [comment]
Sure, I'll transfer the image to the betagouv org.

**Comment by maukoquiroga** [comment]
Seems you still need to rebase before merging. Otherwise GTM.

**Pull request merged**
