### PR TITLE
Remove client from assigns

### PR DESCRIPTION
**Pull request by l-vincent-l**
there is a lot of private values in here.
It might be exposed during a failure.

### CODE REVIEW

**Comment by maukoquiroga** [comment]
What were we using it for in the first place ? Shouldn't we remove it from the session also ?

**Comment by l-vincent-l** [comment]
I don't know, I'll check

**Comment by l-vincent-l** [comment]
In the session the client is needed by our oauth component

**Comment by l-vincent-l** [comment]
I have some problems with this one, I'm still working on it.

**Comment by l-vincent-l** [comment]
This is ok now

**Pull request merged**
